### PR TITLE
feat(nonen): Added more polish sources and fixed indexing by names.

### PR DESCRIPTION
**Pull request by DzikStar**

### CODE REVIEW

**Comment by anotherduckling** [comment]
both of them are for sale.

image

image

**Comment by DzikStar** [comment]
I noticed last night. The author has been promising for two years to continue the Wbijam and TMJ projects even though he had problems with the tax office, last week he said that he would rather close the project, but a moment later he announced that he was giving up and would continue these projects, but yesterday, strangely enough, these domains have been put up for sale.

Will we close this PR or will we just replace the current links for TMJ and Wbijam with links from webarchive saves? Both projects were great and provided original Polish translations with a really high translations quality standard, so it would be good to keep a link to the website.

**Comment by anotherduckling** [comment]
We can probably add web achieve version if it contains a lot of files. adding main url at this point can push scam since the owner has given up.

**Comment by DzikStar** [comment]
I have replaced links, removed TMJ and added Wbijam players database so peoples could easily find out selected episodes if webarchive would redirect to non-existing link instead to player page.

**Pull request merged**
